services:
  - type: web
    name: subhub
    runtime: docker
    dockerfilePath: ./Dockerfile
    branch: main
    healthCheckPath: /index.php
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        value: a_store
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: PHP_MEMORY_LIMIT
        value: 256M
